version: '3.8'
services:
  application:
    container_name: rest_api
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"



